#
# IMPORTANT.  OS X support is so experimental that you have to specifically
# request to have it enabled, on a per-repository basis.  See
# http://docs.travis-ci.com/user/multi-os/#Manual-intervention-required
#
# This file will still work, without OS X enabled, it just won't run those
# tests.
#
# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
# language: python
language: c

os:
    - linux
    # - osx

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# SPECEX and HARP.  Once we are building specex, we need C++11
# features that require a newer OS and gcc.  These two lines
# switch us to non-container, Ubuntu 14.04
#sudo: required
#dist: trusty

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        # - NUMPY_VERSION=1.10
        # - SCIPY_VERSION=0.16
        - ASTROPY_VERSION=2.0.8
        - SPHINX_VERSION=1.6.6
        - DESIUTIL_VERSION=1.9.13
        - MAIN_CMD='python setup.py'
        # These packages will always be installed.
        - CONDA_DEPENDENCIES=""
        # These packages will only be installed if we really need them.
        - CONDA_ALL_DEPENDENCIES="scipy sklearn matplotlib"
        # These packages will always be installed.
        - PIP_DEPENDENCIES=""
        # These packages will only be installed if we really need them.
        - PIP_ALL_DEPENDENCIES="coveralls"
        # These pip packages need to be installed in a certain order, so we
        # do that separately from the astropy/ci-helpers scripts.
        - DESIHUB_PIP_DEPENDENCIES="desiutil=${DESIUTIL_VERSION}"
        # Debug the Travis install process.
        - DEBUG=False
    matrix:
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='bdist_egg'
        - PYTHON_VERSION=3.6 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.6 SETUP_CMD='bdist_egg'

matrix:
    # Don't wait for allowed failures.
    fast_finish: true

    # OS X support is still experimental, so don't penalize failuures.
    allow_failures:
        - os: osx

    include:

        # Check for sphinx doc build warnings - we do this first because it
        # runs for a long time
        - os: linux
          env: PYTHON_VERSION=3.6 SETUP_CMD='build_sphinx --warning-is-error'
        #         CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
        #         PIP_DEPENDENCIES=$PIP_ALL_DEPENDENCIES

        # Do a bdist_egg compile.  This will catch things like syntax errors
        # without needing to do a full python setup.py test
        - os: linux
          env: PYTHON_VERSION=3.6 SETUP_CMD='bdist_egg'

        # Default versions
        - os: linux
          env: PYTHON_VERSION=3.6 SETUP_CMD='test --coverage'
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               PIP_DEPENDENCIES=$PIP_ALL_DEPENDENCIES

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    # egg_info causes the astropy/ci-helpers script to exit before the pip
    # packages are installed, thus desiutil is not installed in that script.
    - for p in $DESIHUB_PIP_DEPENDENCIES; do r=$(echo $p | cut -d= -f1); v=$(echo $p | cut -d= -f2); pip install git+https://github.com/desihub/${r}.git@${v}#egg=${r}; done

before_install:
    # Show the Travis worker's IP address.
    # - curl ipinfo.io
    # setup fake X11 server; QA tests may need this
    # see https://docs.travis-ci.com/user/gui-and-headless-browsers/
    # - "export DISPLAY=:99.0"
    # - "sh -e /etc/init.d/xvfb start"
    # - sleep 3  # give xvfb some time to start
    # See how the locale is set.
    - echo LC_ALL=${LC_ALL:-undef} LC_CTYPE=${LC_CTYPE:-undef} LANG=${LANG:-undef} LANGUAGE=${LANGUAGE:-undef}

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls; fi
