#
# IMPORTANT.  OS X support is so experimental that you have to specifically
# request to have it enabled, on a per-repository basis.  See
# http://docs.travis-ci.com/user/multi-os/#Manual-intervention-required
#
# This file will still work, without OS X enabled, it just won't run those
# tests.
#
language: python

os:
    - linux
    # - osx

# As of early 2017, the default Linux environment is Ubuntu 12.04 (precise).
# This will soon change to 14.04 (trusty). To prepare, set it explicitly.
dist: trusty
# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
python:
    - 3.5
    - 3.6
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - MAIN_CMD='python setup.py'
        # These packages will always be installed.
        - CONDA_DEPENDENCIES=""
        # These packages will only be installed if we really need them.
        - CONDA_ALL_DEPENDENCIES="scipy matplotlib"
    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='bdist_egg'
        - SETUP_CMD='test'

matrix:
    # Don't wait for allowed failures.
    fast_finish: true

    # OS X support is still experimental, so don't penalize failures.
    allow_failures:
        - os: osx
        - os: linux
          python: 3.5
          env: MAIN_CMD='pycodestyle' SETUP_CMD='--count py/desietc'

    include:
        # Check for sphinx doc build warnings - we do this first because it
        # runs for a long time
        - os: linux
          python: 3.5
          env: SETUP_CMD='build_sphinx --warning-is-error'

        # Do a bdist_egg compile.  This will catch things like syntax errors
        # without needing to do a full python setup.py test
        - os: linux
          python: 3.5
          env: SETUP_CMD='bdist_egg'

        # Default versions
        - os: linux
          python: 3.5
          env: SETUP_CMD='test'
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES

        # Default versions
        - os: linux
          python: 3.6
          env: SETUP_CMD='test'
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES

        # Coverage test, pass the results to coveralls.
        - os: linux
          python: 3.5
          env: SETUP_CMD='test --coverage'
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES

        # Experimental OS X test.
        # As of March 2017, Python builds on OS X are not available.
        # See https://docs.travis-ci.com/user/languages/python/
        # - os: osx
        #   python: 3.5
        #   env: SETUP_CMD='test'

        # PEP 8 compliance.
        - os: linux
          python: 3.5
          env: MAIN_CMD='pycodestyle' SETUP_CMD='--count py/desietc'

before_install:
    - curl ipinfo.io

install:
    - if [[ $MAIN_CMD == 'pycodestyle' ]]; then pip install pycodestyle; fi
    - if [[ $SETUP_CMD == build_sphinx* ]]; then pip install Sphinx; fi
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then pip install coverage coveralls; fi
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls; fi
